name: nerd_facts_project
version: '1.0'
config-version: 2

profile: nerd_facts_profile

source-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

seeds:
  nerd_facts_project:
    +schema: seeds
