name: "nerd_facts"

profile: "duckdb"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"] 

clean-targets:         
  - "target"
  - "dbt_packages"  

models:
  nerd_facts:
    +schema: raw