nerd_facts_profile:
  outputs:
    dev:
      type: duckdb
      path: "/home/janne/nerd-facts-replacement/dbt_project/data/nerd_facts.duckdb"  # Use absolute path
      schema: main  # Default schema for dimensions and junctions
      threads: 4  # Adjust based on system capacity
  target: dev
