version: 2

models:
  # ✅ SWAPI Dimensions (Star Wars API)
  - name: swapi_dim_films
    description: "Film details from Star Wars"
    columns:
      - name: film_id
        tests:
          - unique
          - not_null
      - name: title
      - name: episode_id
      - name: director
      - name: producer
      - name: release_date
        tests:
          - not_null
      - name: opening_crawl

  - name: swapi_dim_people
    description: "Characters from Star Wars"
    columns:
      - name: character_id
        tests:
          - unique
          - not_null
      - name: name
      - name: gender
      - name: skin_color
      - name: hair_color
      - name: eye_color
      - name: height_cm
      - name: weight_kg
      - name: birth_year
      - name: homeworld_id
        tests:
          - relationships:
              to: ref('swapi_dim_planets')
              field: planet_id

  - name: swapi_dim_planets
    description: "Planets in the Star Wars universe"
    columns:
      - name: planet_id
        tests:
          - unique
          - not_null
      - name: name
      - name: diameter_km
      - name: climate
      - name: terrain
      - name: population
      - name: gravity

  # ✅ Netrunner Dimensions
  - name: netrunner_dim_cards
    description: "Netrunner card details"
    columns:
      - name: card_code
        tests:
          - unique
          - not_null
      - name: card_name
      - name: card_type
      - name: faction
      - name: pack_code
      - name: side_code
      - name: created_at
      - name: updated_at
      - name: card_text
      - name: is_unique

  - name: netrunner_dim_cycles
    description: "Netrunner expansion cycles"
    columns:
      - name: cycle_code
        tests:
          - unique
          - not_null
      - name: cycle_name
      - name: cycle_position
      - name: cycle_size
      - name: is_rotated

  # ✅ PokéAPI Dimensions
  - name: pokemon_dim_pokemon
    description: "Pokémon details"
    columns:
      - name: pokemon_id
        tests:
          - unique
          - not_null
      - name: name
      - name: height
      - name: weight
      - name: base_experience
      - name: type

  - name: pokemon_dim_species
    description: "Pokémon species details"
    columns:
      - name: species_id
        tests:
          - unique
          - not_null
      - name: name
      - name: color
      - name: habitat
      - name: shape
      - name: base_happiness
      - name: capture_rate
