version: 2

sources:
  - name: staging
    schema: staging
    tables:
      - name: raw_swapi_people
        external:
          location: "/home/janne/nerd-facts-replacement/staging_data/swapi_people.parquet"
          format: parquet
