version: 2

models:
  # ✅ SWAPI Junctions (Star Wars API)
  - name: swapi_junction_films_characters
    description: "Many-to-many relationship between films and characters"
    columns:
      - name: film_id
        tests:
          - not_null
          - relationships:
              to: ref('swapi_dim_films')
              field: film_id
      - name: character_id
        tests:
          - not_null
          - relationships:
              to: ref('swapi_dim_people')
              field: character_id

  - name: swapi_junction_species_people
    description: "Many-to-many relationship between species and people"
    columns:
      - name: species_id
        tests:
          - not_null
          - relationships:
              to: ref('swapi_dim_species')
              field: species_id
      - name: character_id
        tests:
          - not_null
          - relationships:
              to: ref('swapi_dim_people')
              field: character_id

  # ✅ PokéAPI Junctions
  - name: pokemon_junction_types
    description: "Junction table for Pokémon and their types"
    columns:
      - name: pokemon_id
        tests:
          - relationships:
              to: ref('pokemon_dim_pokemon')
              field: pokemon_id
      - name: type_id
        tests:
          - relationships:
              to: ref('pokemon_dim_types')
              field: type_id

  - name: pokemon_junction_moves
    description: "Junction table for Pokémon and their moves"
    columns:
      - name: pokemon_id
        tests:
          - relationships:
              to: ref('pokemon_dim_pokemon')
              field: pokemon_id
      - name: move_id
        tests:
          - relationships:
              to: ref('pokemon_dim_moves')
              field: move_id
