version: 2

sources:
  - name: nerd_facts_raw
    schema: staging
    tables:
      - name: films
      - name: people
      - name: planets
      - name: species
      - name: starships
      - name: vehicles      
