version: 2

sources:
  - name: raw
    description: "Raw data from APIs (SWAPI, NetrunnerDB, PokéAPI)"
    schema: raw

    # ✅ SWAPI TABLES (Already present)
    tables:
      - name: films
        description: "Raw data for films from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null
      - name: people
        description: "Raw data for people (characters) from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null
      - name: planets
        description: "Raw data for planets from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null
      - name: starships
        description: "Raw data for starships from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null
      - name: vehicles
        description: "Raw data for vehicles from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null
      - name: species
        description: "Raw data for species from SWAPI"
        columns:
          - name: uid
            tests:
              - unique
              - not_null

    # ✅ NETRUNNERDB TABLES
      - name: netrunner_cards
        description: "Raw data for Netrunner cards"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_cycles
        description: "Raw data for Netrunner cycles"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_factions
        description: "Raw data for Netrunner factions"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_packs
        description: "Raw data for Netrunner packs"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_sides
        description: "Raw data for Netrunner sides"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_types
        description: "Raw data for Netrunner card types"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_prebuilts
        description: "Raw data for Netrunner prebuilt decks"
        columns:
          - name: code
            tests:
              - unique
              - not_null
      - name: netrunner_reviews
        description: "Raw data for Netrunner card reviews"
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: netrunner_rulings
        description: "Raw data for Netrunner card rulings"
        columns:
          - name: title
            tests:
              - not_null

    # ✅ POKÉAPI TABLES (Newly added)
      - name: pokemon_pokemon
        description: "Raw data for Pokémon details"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
          - name: height
          - name: weight
          - name: types
          - name: base_experience

      - name: pokemon_pokemon_species
        description: "Raw data for Pokémon species"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
          - name: color
          - name: habitat
          - name: shape
          - name: base_happiness
          - name: capture_rate

      - name: pokemon_ability
        description: "Raw data for Pokémon abilities"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
          - name: is_main_series

      - name: pokemon_move
        description: "Raw data for Pokémon moves"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
          - name: power
          - name: accuracy
          - name: pp
          - name: priority
          - name: damage_class
          - name: type

      - name: pokemon_type
        description: "Raw data for Pokémon types"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name

      - name: pokemon_evolution_chain
        description: "Raw Pokémon evolution chain data"    

      - name: pokemon_stat
        description: "Raw Pokémon stat data"               
